module.exports = {
  siteMetadata: {
    htmlLang: "en",
    contenLang: "en-us",
    title: "Atlanta Vote Helper",
    titleTemplate: "%s · Atlanta Vote Helper",
    description:
      "An FAQ page for people who want to vote in Atlanta elections.",
    siteUrl: "https://atlvoterhelper.netlify.app",
    siteName: "A Help Center Theme for Gatsby",
    logoUrl: "/images/peach.png",
    logoLabel: "Atlanta Vote Helper",
    searchText: "Search",
    faviconUrl: "/images/favicon.png",
    socialSharingImageUrl: "/images/social-sharing-preview.png",
    twitter: "",
    facebookUrl: "",
    ctaButtonText: "Open source on GitHub",
    ctaButtonUrl: "https://github.com/Bartlebyy/atlanta-voter-helper",
    linkText: "",
    linkUrl: "https://atlvoterhelper.netlify.app",
    headline: "What voting-related question do you have?",
    footerText: "About me",
    footerUrl: "https://diego.medina.codes",
    googleTagManagerId: "",
    googleAnalyticsMeasurementId: "",
  },
  plugins: ["gatsby-plugin-typescript", "@mlent/gatsby-theme-help-center"],
};
